# Generated by Django 5.2.12 on 2026-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
